import vvoda from '../images/vvoda-sboku.png';
import so_zav from '../images/so-zav.png';
import so_nezav from '../images/so-nezav.png';
import gvs from '../images/gvs-one-step-sboku.png';
import gvs_monoblok from '../images/gvs-two-step-sboku.png';
 
const btpIngreds = [
    {
        "_id":"60666c42cc7b410027a1a9b50",
        "name":"Узел УВУУ с КЗТ",
        "type":"uvuu",
        "price":3000,
        "image": vvoda,
        "scheme": "vvoda.svg",
        "specification": [{"id":1,"name":" Кран шаровый, стандартнопроходной, фланцевый, PN16, DN","quantity":4,"category":"fittings"},{"id":2,"name":" Фильтр сетчатый, фланцевый, PN16, DN","quantity":2,"category":"fittings"},{"id":3,"name":" Биметаллический термометр с гильзой, шкала 0-160°С","quantity":2,"category":"kipAndOthers"},{"id":4,"name":" Манометр, шкала 0-16 бар","quantity":11,"category":"kipAndOthers"},{"id":5,"name":" Кран для подключения манометра, PN16, DN15","quantity":11,"category":"fittings"},{"id":6,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":5,"category":"fittings"},{"id":7,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":4,"category":"fittings"},{"id":8,"name":" Кран шаровый, муфтовый, с дренажем и воздухоотвод-ом, латунь, DN15","quantity":4,"category":"fittings"},{"id":9,"name":" Расходомер PN16, DN","quantity":2,"category":"kipDn"},{"id":10,"name":" Тепловычислитель (в комплекте с GSM модемом)","quantity":1,"category":"kipAndOthers"},{"id":11,"name":" Комплект термопреобразователей сопротивления (0…180°C)","quantity":1,"category":"kipAndOthers"},{"id":12,"name":" Защитная гильза","quantity":2,"category":"kipAndOthers"},{"id":13,"name":" Грязевик абонентский, PN10, DN","quantity":2,"category":"fittings"},{"id":14,"name":" Датчик давления, 4-20мА, (0-16МПа)","quantity":2,"category":"kipAndOthers"},{"id":15,"name":" Расходомер, PN16, DN","quantity":1,"category":"kipDn"},{"id":16,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":2,"category":"fittings"},{"id":17,"name":" Фильтр сетчатый, муфтовый, латунь, PN25, DN","quantity":1,"category":"fittings"},{"id":18,"name":" Регулятор перепада давления","quantity":1,"category":"valves"},{"id":19,"name":"Воздухоотводчик автоматический, PN10","quantity":2,"category":"kipAndOthers"}],
        "__v":0
     },
     {
        "_id":"60666c42cc7b410027a1a9b51",
        "name":"Узел CО зависимая",
        "type":"so",
        "price":3000,
        "specification": [{"id":1,"name":" Насос (циркуляционный)","quantity":2,"category":"nasosy"},{"id":2,"name":" Двухходовой регулирующий клапан (с электроприводом), Kvs=, DN","quantity":1,"category":"valves"},{"id":3,"name":" Кран шаровый, стандартнопроходной, фланцевый, PN16, DN","quantity":2,"category":"fittings"},{"id":4,"name":" Кран шаровый, стандартнопроходной, фланцевый, PN16, DN","quantity":2,"category":"fittings"},{"id":5,"name":" Затвор дисковый, PN16, DN","quantity":5,"category":"fittings"},{"id":6,"name":" Клапан обратный, межфланцевый, PN16, DN","quantity":3,"category":"fittings"},{"id":7,"name":" Фильтр сетчатый, фланцевый, PN16, DN","quantity":1,"category":"fittings"},{"id":8,"name":" Манометр, шкала 0-16 бар","quantity":9,"category":"kipAndOthers"},{"id":9,"name":" Кран для подключения манометра, PN16, DN15","quantity":9,"category":"fittings"},{"id":10,"name":" Биметаллический термометр с гильзой, шкала 0-160°С","quantity":4,"category":"kipAndOthers"},{"id":11,"name":" Датчик температуры","quantity":2,"category":"kipAndOthers"},{"id":12,"name":" Защитная гильза","quantity":2,"category":"kipAndOthers"},{"id":13,"name":" Реле перепада давления","quantity":1,"category":"kipAndOthers"},{"id":14,"name":" Реле давления (0,3 МПа)","quantity":1,"category":"kipAndOthers"},{"id":15,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":4,"category":"fittings"},{"id":16,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":2,"category":"fittings"},{"id":17,"name":" Кран шаровый, муфтовый, с дренажем и воздухоотвод-ом, латунь, DN15","quantity":3,"category":"fittings"},{"id":18,"name":" Клапан балансировочный, PN16, DN","quantity":1,"category":"valves"}],
        "image": so_zav,
        "__v":0
     },
     {
        "_id":"60666c42cc7b410027a1a9b52",
        "name":"Узел CО независимая",
        "type":"so",
        "price":3000,
        "specification": [{"id":1,"name":" Пластинчатый теплообменник","quantity":1,"category":"pto"},{"id":2,"name":" Насос (циркуляционный)","quantity":2,"category":"nasosy"},{"id":3,"name":" Двухходовой регулирующий клапан (с электроприводом), Kvs=, DN","quantity":1,"category":"valves"},{"id":4,"name":" Фильтр сетчатый, фланцевый, PN16, DN","quantity":1,"category":"fittings"},{"id":5,"name":" Кран шаровый, стандартнопроходной, фланцевый, PN16, DN","quantity":2,"category":"fittings"},{"id":6,"name":" Кран шаровый, стандартнопроходной, фланцевый, PN16, DN","quantity":2,"category":"fittings"},{"id":7,"name":" Затвор дисковый, PN16, DN","quantity":4,"category":"fittings"},{"id":8,"name":" Клапан обратный, межфланцевый, PN16, DN","quantity":2,"category":"fittings"},{"id":9,"name":" Биметаллический термометр с гильзой, шкала 0-160°С","quantity":4,"category":"kipAndOthers"},{"id":10,"name":" Манометр, шкала 0-16 бар","quantity":13,"category":"kipAndOthers"},{"id":11,"name":" Кран для подключения манометра, PN16, DN15","quantity":13,"category":"fittings"},{"id":12,"name":" Реле давления (1,0 МПа)","quantity":1,"category":"kipAndOthers"},{"id":13,"name":" Реле перепада давления","quantity":1,"category":"kipAndOthers"},{"id":14,"name":" Датчик температуры","quantity":2,"category":"kipAndOthers"},{"id":15,"name":" Защитная гильза","quantity":2,"category":"kipAndOthers"},{"id":16,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":4,"category":"fittings"},{"id":17,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":2,"category":"fittings"},{"id":18,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":3,"category":"fittings"},{"id":19,"name":" Клапан обратный, муфтовый, латунь, PN25, DN","quantity":1,"category":"fittings"},{"id":20,"name":" Клапан предохранительный, Pсраб=1,0-12,0 бар","quantity":2,"category":"valves"},{"id":21,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":7,"category":"fittings"},{"id":22,"name":" Электромагнитный клапан, двухходовой, PN25, DN","quantity":1,"category":"fittings"},{"id":23,"name":" Мембранный расширительный бак, V= (л)","quantity":2,"category":"tank"},{"id":24,"name":" Реле давления (0,3 МПа)","quantity":2,"category":"kipAndOthers"},{"id":25,"name":" Кран шаровый, муфтовый, с дренажем и воздухоотвод-ом, латунь, DN15","quantity":5,"category":"fittings"},{"id":26,"name":" Насос (подпиточный)","quantity":1,"category":"nasosy"}],
        "image": so_nezav,
        "__v":0
     },
     {
      "_id":"60666c42cc7b410027a1a9b5113",
      "name":"Узел ГВС",
      "type":"gvs",
      "price":3000,
      "image": gvs,
      "specification": [{"id":1,"name":" Пластинчатый теплообменник","quantity":1,"category":"pto"},{"id":2,"name":" Насос (циркуляционный)","quantity":2,"category":"nasosy"},{"id":3,"name":" Двухходовой регулирующий клапан (с электроприводом), Kvs=, DN","quantity":1,"category":"valves"},{"id":4,"name":" Фильтр сетчатый, муфтовый, латунь, PN25, DN","quantity":1,"category":"fittings"},{"id":5,"name":" Клапан обратный, муфтовый, латунь, PN25, DN","quantity":2,"category":"fittings"},{"id":6,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":5,"category":"fittings"},{"id":7,"name":" Фильтр сетчатый, муфтовый, латунь, PN25, DN","quantity":1,"category":"fittings"},{"id":8,"name":" Клапан обратный, муфтовый, латунь, PN25, DN","quantity":1,"category":"fittings"},{"id":9,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":3,"category":"fittings"},{"id":10,"name":" Кран шаровый, стандартнопроходной, фланцевый, PN16, DN","quantity":2,"category":"fittings"},{"id":11,"name":" Манометр, шкала 0-16 бар","quantity":13,"category":"kipAndOthers"},{"id":12,"name":" Кран для подключения манометра, PN16, DN15","quantity":13,"category":"fittings"},{"id":13,"name":" Счетчик холодной воды, PN16, DN","quantity":1,"category":"kipDn"},{"id":14,"name":" Реле перепада давления","quantity":1,"category":"kipAndOthers"},{"id":15,"name":" Биметаллический термометр с гильзой, шкала 0-160°С","quantity":5,"category":"kipAndOthers"},{"id":16,"name":" Датчик температуры","quantity":1,"category":"kipAndOthers"},{"id":17,"name":" Защитная гильза","quantity":1,"category":"kipAndOthers"},{"id":18,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":4,"category":"fittings"},{"id":19,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":2,"category":"fittings"},{"id":20,"name":" Клапан предохранительный, Pсраб=1,0-12,0 бар","quantity":1,"category":"fittings"},{"id":21,"name":" Клапан балансировочный, PN16, DN","quantity":1,"category":"valves"},{"id":22,"name":" Реле давления (0,3 МПа)","quantity":1,"category":"kipAndOthers"},{"id":23,"name":" Кран шаровый, муфтовый, с дренажем и воздухоотвод-ом, латунь, DN15","quantity":3,"category":"fittings"}],
      "__v":0
   },
   {
      "_id":"60666c42cc7b410027a1a9b5223",
      "name":"Узел ГВС моноблок",
      "type":"gvs",
      "specification": [{"id":1,"name":" Пластинчатый теплообменник","quantity":1,"category":"pto"},{"id":2,"name":" Насос (циркуляционный)","quantity":2,"category":"nasosy"},{"id":3,"name":" Двухходовой регулирующий клапан (с электроприводом), Kvs=, DN","quantity":1,"category":"valves"},{"id":4,"name":" Фильтр сетчатый, муфтовый, латунь, PN25, DN","quantity":1,"category":"fittings"},{"id":5,"name":" Клапан обратный, муфтовый, латунь, PN25, DN","quantity":2,"category":"fittings"},{"id":6,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":5,"category":"fittings"},{"id":7,"name":" Фильтр сетчатый, муфтовый, латунь, PN25, DN","quantity":1,"category":"fittings"},{"id":8,"name":" Клапан обратный, муфтовый, латунь, PN25, DN","quantity":1,"category":"fittings"},{"id":9,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":2,"category":"fittings"},{"id":10,"name":" Кран шаровый, стандартнопроходной, фланцевый, PN16, DN","quantity":1,"category":"fittings"},{"id":11,"name":" Манометр, шкала 0-16 бар","quantity":14,"category":"kipAndOthers"},{"id":12,"name":" Кран для подключения манометра, PN16, DN15","quantity":14,"category":"kipAndOthers"},{"id":13,"name":" Счетчик холодной воды, PN16, DN","quantity":1,"category":"kipDn"},{"id":14,"name":" Реле перепада давления","quantity":1,"category":"kipAndOthers"},{"id":15,"name":" Биметаллический термометр с гильзой, шкала 0-160°С","quantity":6,"category":"kipAndOthers"},{"id":16,"name":" Датчик температуры","quantity":1,"category":"kipAndOthers"},{"id":17,"name":" Защитная гильза","quantity":1,"category":"kipAndOthers"},{"id":18,"name":" Кран шаровый, стандартнопроходной, фланцевый, PN16, DN","quantity":1,"category":"fittings"},{"id":19,"name":" Кран шаровый, стандартнопроходной, фланцевый, PN16, DN","quantity":1,"category":"fittings"},{"id":20,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":6,"category":"fittings"},{"id":21,"name":" Кран шаровый, муфтовый, латунь, PN25, DN","quantity":2,"category":"fittings"},{"id":22,"name":" Клапан предохранительный, Pсраб=1,0-12,0 бар","quantity":1,"category":"fittings"},{"id":23,"name":" Клапан балансировочный, PN16, DN","quantity":1,"category":"valves"},{"id":24,"name":" Реле давления (0,3 МПа)","quantity":1,"category":"kipAndOthers"},{"id":25,"name":" Кран шаровый, муфтовый, с дренажем и воздухоотвод-ом, латунь, DN15","quantity":3,"category":"fittings"},{"id":26,"name":"Кран шаровой стандартнопроходной Regula, PN16, DN","quantity":1,"category":"fittings"}],
      "image": gvs_monoblok,
      "__v":0
   }
];

export default btpIngreds;